### ISSUE TITLE
meta

### ISSUE THREAD

**Issue by bidva** [digia/jaysonapi#13]
How to add meta tag to collection ?

**Comment by bidva** [comment]
@digia ?

**Comment by digia** [comment]
Hey @bidva, it's been a minute since I've worked with the library, but if I recall correctly passing `meta` to `.serialize()` will simply pass it through to the output.

```javascript
const data = {};
const meta = {};

const jsonapi = YourSerializer.serialize({ data, meta });

// meta === jsonapi.meta
``` 

https://github.com/digia/jaysonapi/blob/7e978fe73c781d02745946326df7764aeff9482f/src/index.js#L235
