### ISSUE TITLE
Pagination links should not go directly in links object

### ISSUE THREAD

**Issue by jpadilla** [digia/jaysonapi#7]
According to the spec, pagination keys `first`, `last`, `prev`, and `next` should in the links object. This library currently forces you to add them in `links.pagination`. I can get a PR together if we agree.

> Pagination links MUST appear in the links object that corresponds to a collection. To paginate the primary data, supply pagination links in the top-level links object. To paginate an included collection returned in a compound document, supply pagination links in the corresponding links object.
> 
> The following keys MUST be used for pagination links:
> - first: the first page of data
> - last: the last page of data
> - prev: the previous page of data
> - next: the next page of data

**Comment by digia** [comment]
It should be inline with the spec. I've been adding things as i run into them on my project.

A PR for this would be greatly appreciated.

Thank you!
