### ISSUE TITLE
Run tests on a CI like Travis

### ISSUE THREAD

**Issue by jpadilla** [digia/jaysonapi#9]
@digia just noticed this project has tests but they are currently not being run in a CI like Travis. It'd be useful to have badge with current status. It'd also help in PRs. I can put together a .travis.yml file if you're interested.

**Comment by jpadilla** [comment]
Note: Seems like mocha is the current way to run the tests instead of lab

**Comment by digia** [comment]
Travis would be a welcome addition. 

Not married to the lab idea. Should be able to hot swap if i recall.
